#!/usr/bin/env python3
"""Generate an index.html for a directory of map_NNN_tsXX_WxH.png files.

Stacks every map vertically with a header showing map index, tileset,
and dimensions. Each map keeps its native pixel scale (PNGs are 2x;
the page renders them pixel-perfect with image-rendering: pixelated).

Usage:
    make_gallery_html.py <maps_dir>
    -> writes <maps_dir>/index.html
"""
import os, sys, re, argparse, html

ENTRY = re.compile(r'^map_(\d+)_ts([0-9A-Fa-f]+)_(\d+)x(\d+)\.png$')

HTML_HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Kirby's Adventure — all maps</title>
<style>
  html, body { margin: 0; padding: 0; background: #111; color: #ddd; font-family: ui-monospace, Menlo, Consolas, monospace; }
  header { position: sticky; top: 0; background: #0a0a0a; padding: 12px 20px; border-bottom: 1px solid #333; z-index: 10; }
  header h1 { margin: 0 0 4px 0; font-size: 16px; font-weight: 600; }
  header .meta { font-size: 12px; color: #888; }
  .toc { padding: 16px 20px; columns: 6; column-gap: 16px; font-size: 11px; line-height: 1.5; background: #161616; border-bottom: 1px solid #333; }
  .toc a { color: #6cf; text-decoration: none; }
  .toc a:hover { text-decoration: underline; }
  .map { padding: 20px; border-bottom: 1px solid #222; scroll-margin-top: 60px; }
  .map h2 { margin: 0 0 8px 0; font-size: 14px; color: #fff; font-weight: 600; }
  .map .info { font-size: 12px; color: #888; margin-bottom: 10px; }
  .map img { image-rendering: pixelated; image-rendering: crisp-edges; display: block; max-width: 100%; background: #000; }
  footer { padding: 20px; font-size: 12px; color: #666; text-align: center; }
</style>
</head>
<body>
<header>
  <h1>Kirby's Adventure — all maps rendered from ROM</h1>
  <div class="meta">$N maps · rendered directly from PRG/CHR data (no FCEUX trace). Scroll, or jump via the index below.</div>
</header>
<div class="toc">
$TOC
</div>
"""

HTML_TAIL = """
<footer>Generated by tools/make_gallery_html.py — pixel-perfect (image-rendering: pixelated).</footer>
</body>
</html>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('dir')
    args = ap.parse_args()

    entries = []
    for fn in sorted(os.listdir(args.dir)):
        m = ENTRY.match(fn)
        if m:
            entries.append((int(m.group(1)), int(m.group(2), 16), int(m.group(3)), int(m.group(4)), fn))
    if not entries:
        print(f'No map_*.png files found in {args.dir}')
        sys.exit(1)

    toc_links = ' '.join(
        f'<a href="#m{idx:03d}">{idx:03d}</a>'
        for idx, _ts, _w, _h, _fn in entries
    )

    body_parts = []
    for idx, ts, w, h, fn in entries:
        body_parts.append(
            f'<div class="map" id="m{idx:03d}">\n'
            f'  <h2>map {idx:03d}</h2>\n'
            f'  <div class="info">tileset ${ts:02X} · {w}×{h} screens · <a href="{html.escape(fn)}" style="color:#888">{html.escape(fn)}</a></div>\n'
            f'  <img src="{html.escape(fn)}" alt="map {idx}" loading="lazy">\n'
            f'</div>\n'
        )

    head = HTML_HEAD.replace('$N', str(len(entries))).replace('$TOC', toc_links)
    out = head + '\n'.join(body_parts) + HTML_TAIL

    out_path = os.path.join(args.dir, 'index.html')
    with open(out_path, 'w') as f:
        f.write(out)
    print(f'Wrote {out_path} ({len(entries)} maps)')


if __name__ == '__main__':
    main()
